apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-etl-pipeline-deployment
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: ECR_IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8501
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"