apiVersion: v1
kind: Service
metadata:
  name: ecommerce-etl-pipeline-service
spec:
  type: LoadBalancer
  selector:
    app: myapp
  ports:
    - name: http
      protocol: TCP
      port: 80         # Standard web port exposed by AWS Load Balancer
      targetPort: 8501 # Application container port